import { productType } from "@/app/store/PraductInfo";

export const ProductData: productType[] = [
    {
        id: 1,
        name: "Qum rasmi",
        price: "165 000 ",
        category: 'unusual',
        cost: "so'm / 1 dona",
        images: [
            {
                id: 1,
                image: "/products/a/a-1.webp",
                vidio: "/watch.MP4"
            },
            {
                id: 2,
                image: "/products/a/a-2.webp",
                vidio: ""
            },
            {
                id: 3,
                image: "/products/a/a-3.webp",
                vidio: ""
            },
            {
                id: 4,
                image: "/products/a/a-4.webp",
                vidio: ""
            }
        ],
        description: "Qum rasmi tunda yonadi, yaqinlaringiz uchun ajoyib sovg'a bo'ladi",
        discountPrice: 0,
        criterion: "1 dona",
    },
    {
        id: 2,
        name: "Oy chiroq",
        price: "300 000 ",
        category: 'unusual',
        cost: "so'm / 1 dona",
        images: [
            {
            id: 1,
            image: "/products/a/a-2.webp",
            vidio: ""
            }
        ],
        description: "Oy chiroq tunda yonadi, yaqinlaringiz uchun ajoyib sovg'a bo'ladi",
        discountPrice: 0,
        criterion: "1 dona",
    },
    {
        id: 3,
        name: "Ring zikir",
        price: "150 000 ",
        category: 'unusual',
        cost: "so'm / 1 dona",
        images: [
            {
                id: 1,
                image: "/products/a/a-3.webp",
                vidio: ""
            }
        ],
        description: `Zikr Tasbeh Smart Uzuk
                        OLED Display Vaqtni ko'rsatib turadi 
                        Bluetooth orqali telefonga ulasa bo'ladi 
                        Android, ios programmasi bor 
                        5 Vaqt namoz vaqtini eslatadi 
                        Qibla qaysi tomondaligini aniqlaydi 
                        iQibla (Smart Qibla) dasturida ishledi 
                        Suvga chidamlik`,
        discountPrice: 0,
        criterion: "1 dona",
    },
    {
        id: 4,
        name: "Yorqin kiristal akril chiroq",
        price: "185 000 ",
        category: 'unusual',
        cost: "so'm / 1 dona",
        images: [
            {
                id: 1,
                image: "/products/a/a-4.webp",
                vidio: ""
            }
        ],
        description: `Ulgurji yangi qayta zaryadlanuvchi Usb
                        Yorqin kristalli akril bilan teging
                        Atirgul soya effekti uy yotoq xonasi
                        Yashash xonasi uchun hashamatli stol chirog'i`,
        discountPrice: 0,
        criterion: "1 dona",
    },
    {
        id: 5,
        name: "Ring zikir",
        price: "300 000 ",
        category: 'unusual',
        cost: "so'm / 1 dona",
        images: [
            {
                id: 1,
                image: "/products/a/a-5.webp",
                vidio: ""
            }
        ],
        description: `Zikr Tasbeh Smart Uzuk
                        OLED Display Vaqtni ko'rsatib turadi 
                        Bluetooth orqali telefonga ulasa bo'ladi 
                        Android, ios programmasi bor 
                        5 Vaqt namoz vaqtini eslatadi 
                        Qibla qaysi tomondaligini aniqlaydi 
                        iQibla (Smart Qibla) dasturida ishledi 
                        Suvga chidamlik`,
        discountPrice: 0,
        criterion: "1 dona",
    },
    // {
    //     id: 6,
    //     name: "Magnitli shaxmat 36х36 sm",
    //     price: "195 000 ",
    //     category: 'unusual',
    //     cost: "so'm / 1 dona",
    //     image: "/products/a/a-7.jpeg",
    //     description: "Bolalaringiz uchun ajyib sovg'a shaxmat - bu klassik stol o'yini. Shaxmat taxtasining magnit materiali oddiy shaxmatga qaraganda qulayroq. Bunday o'yinlar bolalarda tafakkur qilishni, kuzatishni va xotirani rivojlantiradi.",
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    {
        id: 6,
        name: "Shisha shaxmat",
        price: "250 000 ",
        category: 'unusual',
        cost: "so'm / 1 dona",
        images: [
            {
                id: 1,
                image: "/products/a/a-1.webp",
                vidio: ""
            }
        ],
        description: "Bolalaringiz uchun ajyib sovg'a Minel shaxmat, shisha, qirol 6 x 2 sm, piyon 3 x 2 sm, doska 24 x 24 sm Shaffof taxtali shisha shaxmat unutilmas sovg'adir. Shaffof va muzli shishadan yasalgan chiroyli figuralar, shaffof hujayrali taxta - bularning barchasi shaxmatga yangi, futuristik ko'rinish beradi.",
        discountPrice: 0,
        criterion: "1 dona",
    },
    {
        id: 7,
        name: "Samoviy tilaklar chirog'i",
        price: "6 000",
        category: 'unusual',
        cost: "so'm / 1 dona",
        images: [
            {
                id: 1,
                image: "/products/a/a-2.webp",
                vidio: ""
            }
        ],
        description: `Samoviy tilaklar chirog'i 
                        Biologik parchalanadigan materiallardan 
                        Parvozning 20 daqiqasidan yuqori 
                        Issiqlikka chidamli material 
                        Rang: marjon 
                        Diametri: 30 sm`,
        discountPrice: 0,
        criterion: "1 dona",
    },
    // {
    //     id: 9,
    //     name: "Samoviy tilaklar chirog'i",
    //     price: "12 000 ",
    //     category: 'unusual',
    //     cost: "so'm / 1 dona",
    //     image: "/products/a/a-10.jpeg",
    //     description: `Samoviy tilaklar chirog'i 
    //                     Biologik parchalanadigan materiallardan 
    //                     Parvozning 20 daqiqasidan yuqori 
    //                     Issiqlikka chidamli material 
    //                     Rang: marjon 
    //                     Diametri: 30 sm`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 10,
    //     name: "Suvi ko'tariladigan Kolba",
    //     price: "28 000 ",
    //     category: 'unusual',
    //     cost: "so'm / 1 dona",
    //    images: [
    //         {
    //             id: 1,
    //             image: "/products/a/a-11.webp",
    //             vidio: ""
    //         }
    //     ],
    //     description: `Yaqin insoningiz uchu ajoyib sovg'a, Ushbu sehrli kolbani tagini ushlasangiz suv tepaga ko'tariladi.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 11,
    //     name: "Bezak uchun qizil atirgul barglar",
    //     price: "16 000 ",
    //     category: 'unusual',
    //     cost: "so'm / 1 dona",
    //     images: [
    //         {
    //             id: 1,
    //             image: "/products/a/a-12.webp",
    //             vidio: ""
    //         }
    //     ],
    //     description: `Bezak uchun qizil atirgul barglar, 300 dona
    //                     300 dona
    //                     Bezak uchun`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 12,
    //     name: "AirPods Pro 2 (Apple Original)",
    //     price: "2 500 000 ",
    //     category: 'accessories',
    //     cost: "so'm / 1 dona",
    //     image: "/products/c/c-1.webp",
    //     description: `Yaqinlaringiz uchun AirPods Pro yanada boy ovozni qayta ishlab chiqarish uchun qayta ishlab chiqilgan. Keyingi darajadagi faol shovqinni bekor qilish va moslashuvchan shaffoflik tashqi shovqinni kamaytiradi. Fazoviy audio hayratlanarli darajada shaxsiy darajaga cho'mishni oladi. Sensorli boshqaruv endi ovoz balandligini bir harakat bilan sozlash imkonini beradi.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 13,
    //     name: "AirPods Pro (Apple Original)",
    //     price: "2 200 000 ",
    //     category: 'accessories',
    //     cost: "so'm / 1 dona",
    //     image: "/products/c/c-2.jpeg",
    //     description: `Yaqinlaringiz uchun ushbu model faol shovqinni bekor qilish bilan jihozlangan bo'lib, u tinglashda tashqi tovushlar va shovqinlarning ta'sirini kamaytirish uchun ishlatiladi. Bluetooth eshitish vositasida shovqinni bekor qilish fondagi shovqinni qabul qiladi va uni filtrlaydi, shunda siz qo'ng'iroq qiluvchining ovozidan boshqa hech qanday tashqi shovqinni eshitmaysiz`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 14,
    //     name: "AirPods 3 (Apple Original)",
    //     price: "2 000 000 ",
    //     category: 'accessories',
    //     cost: "so'm / 1 dona",
    //     image: "/products/c/c-3.webp",
    //     description: `Yaqinlaringiz uchun AirPods 3 – Apple kompaniyasining eng yangi AirPod qurilmalari bo‘lib, ixchamroq kontur, moslashuvchan ekvalayzer, terga chidamlilik, fazoviy audio qo‘llab-quvvatlash, kichikroq stendlar, MagSafe zaryadlash qutisi, moslashuvchan EQ, 30 soatgacha batareya quvvati, IPX4 suv va terga chidamlilik, fazoviy ovoz. , HD FaceTime qo'ng'iroqlariz`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 15,
    //     name: "iPad mini 6 (256 GB, Apple Original)",
    //     price: "5 700 000 ",
    //     category: 'phones',
    //     cost: "so'm / 1 dona",
    //     image: "/products/e/e-1.png",
    //     description: `Yaqinlaringiz uchun "To'liq qayta ishlangan" sifatida tavsiflangan iPad mini 6 kuchli yangi A15 Bionic chipi, 8,3 dyuymli Liquid Retina displey, Apple Pencil 2-ni qo'llab-quvvatlash, yaxshilangan kameralar va 5G ulanishi kabi muhim o'zgarishlarga ega. Bu iPad mini muxlislari kutgan yangilanishdir.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 16,
    //     name: "iPhone 14 (128 GB, Apple Original)",
    //     price: "10 060 000 ",
    //     category: 'phones',
    //     cost: "so'm / 1 dona",
    //     image: "/products/e/e-2.jpeg",
    //     description: `Yaqinlaringiz uchun Tashqi tomondan, iPhone 14 sinovdan o'tgan va haqiqiy iPhone 13 tekis alyuminiy dizaynini meros qilib oladi. Ichkarida Apple iPhone 13 Pro-ni tubdan qayta qadoqlab, telefoto linzalari va yuqori yangilanish tezligi ekranini olib tashladi. Natija chiroyli va iPhone 14 ko'pchilik uchun yaxshi yangilanishdir.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 17,
    //     name: "iPhone 14 Pro (256 GB, Apple Original)",
    //     price: "13 000 000 ",
    //     category: 'phones',
    //     cost: "so'm / 1 dona",
    //     image: "/products/e/e-3.jpeg",
    //     description: `Yaqinlaringiz uchun ajoyib sovg'a. Yuqori vizual yangilanish - bu portlash o'rniga kichik kesish. Datchiklar iPhone displeyi ostida joylashgan, atrofdagi fon stsenariyga ko'ra o'zgartiriladi: AirPod-larni ulash, kiruvchi qo'ng'iroq haqida bildirishnoma va boshqalar. Kontseptsiya "Dinamik orol" - "dinamik orol" deb nomlanadi.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 18,
    //     name: "iPhone 14 Pro Max (256 GB, Apple Original)",
    //     price: "14 000 000 ",
    //     category: 'phones',
    //     cost: "so'm / 1 dona",
    //     image: "/products/e/e-3.jpeg",
    //     description: `Yaqinlaringiz uchun ajoyib sovg'a. Yuqori vizual yangilanish - bu portlash o'rniga kichik kesish. Datchiklar iPhone displeyi ostida joylashgan, atrofdagi fon stsenariyga ko'ra o'zgartiriladi: AirPod-larni ulash, kiruvchi qo'ng'iroq haqida bildirishnoma va boshqalar. Kontseptsiya "Dinamik orol" - "dinamik orol" deb nomlanadi.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 19,
    //     name: "iPhone 13 Pro (128 GB, Apple Original)",
    //     price: "13 200 000 ",
    //     category: 'phones',
    //     cost: "so'm / 1 dona",
    //     image: "/products/e/e-4.jpeg",
    //     description: `Yaqinlaringiz uchun ajoyib sovg'a. iPhone 13 Pro bilan Pro kamera tizimi eng katta yangilanishdan o'tdi. ProMotion bilan Super Retina XDR displey. Ceramic Shield har qanday smartfon oynasidan kuchliroqdir. `,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 20,
    //     name: "iPhone 13 Pro Max (128 GB, Apple Original)",
    //     price: "14 000 000 ",
    //     category: 'phones',
    //     cost: "so'm / 1 dona",
    //     image: "/products/e/e-4.jpeg",
    //     description: `Yaqinlaringiz uchun ajoyib sovg'a. iPhone 13 Pro bilan Pro kamera tizimi eng katta yangilanishdan o'tdi. ProMotion bilan Super Retina XDR displey. Ceramic Shield har qanday smartfon oynasidan kuchliroqdir. `,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 21,
    //     name: "iPhone 13 Pro Max (128 GB, Apple Original)",
    //     price: "14 000 000 ",
    //     category: 'toys',
    //     cost: "so'm / 1 dona",
    //     image: "/products/e/e-4.jpeg",
    //     description: `Yaqinlaringiz uchun ajoyib sovg'a. iPhone 13 Pro bilan Pro kamera tizimi eng katta yangilanishdan o'tdi. ProMotion bilan Super Retina XDR displey. Ceramic Shield har qanday smartfon oynasidan kuchliroqdir. `,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 22,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/GD/g-1.webp",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 23,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/GD/g-2.webp",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 24,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/GD/g-3.webp",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 25,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/GD/g-4.webp",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 26,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/GD/g-5.webp",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 27,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/GD/g-6.webp",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 28,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/GD/g-7.webp",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 29,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/GD/g-8.webp",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 30,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/GD/g-9.webp",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 31,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-10.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 32,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-11.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 33,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-12.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 34,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-13.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 35,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-14.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz. To'y va marosimlarda qo'shimcha dekoratsiya uchun yaxshi tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 36,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-15.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 37,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-16.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 38,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-17.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 39,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-18.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 40,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-19.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 41,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-20.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 42,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-21.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 43,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-22.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 44,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-23.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 45,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-24.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 46,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-25.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 47,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-26.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 48,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-27.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 49,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-28.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 50,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-29.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 51,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-30.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 52,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-31.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 53,
    //     name: "Gullar",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'flowers',
    //     cost: "",
    //     image: "/products/g/TG/g-32.jpg",
    //     description: `Yaqinlaringiz uchun gullar yaxshi tanlov. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va siz xoxlagan insonlaringiz uchun biz sizga yordam beramiz.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },

    // {
    //     id: 54,
    //     name: "Box of gifts",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'holidays',
    //     cost: "",
    //     image: "/products/j/j-1.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 55,
    //     name: "Box of gifts",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'holidays',
    //     cost: "",
    //     image: "/products/j/j-2.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 56,
    //     name: "Box of chocolates",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'beautiful',
    //     cost: "",
    //     image: "/products/j/j-3.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 57,
    //     name: "Box of gifts",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'holidays',
    //     cost: "",
    //     image: "/products/j/j-4.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 58,
    //     name: "Box of gifts",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'holidays',
    //     cost: "",
    //     image: "/products/j/j-5.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 59,
    //     name: "Box of gifts",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'holidays',
    //     cost: "",
    //     image: "/products/j/j-6.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 60,
    //     name: "Box of gifts",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'holidays',
    //     cost: "",
    //     image: "/products/j/j-7.jpg",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 61,
    //     name: "Box of gifts",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'holidays',
    //     cost: "",
    //     image: "/products/j/j-8.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 62,
    //     name: "Box of chocolates",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'beautiful',
    //     cost: "",
    //     image: "/products/j/j-9.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 63,
    //     name: "Box of gifts",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'holidays',
    //     cost: "",
    //     image: "/products/j/j-10.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 64,
    //     name: "Box of gifts",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'holidays',
    //     cost: "",
    //     image: "/products/j/j-11.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 65,
    //     name: "Box of gifts",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'holidays',
    //     cost: "",
    //     image: "/products/j/j-12.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 66,
    //     name: "Box of gifts",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'holidays',
    //     cost: "",
    //     image: "/products/j/j-13.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 67,
    //     name: "Box of gifts",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'holidays',
    //     cost: "",
    //     image: "/products/j/j-14.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 68,
    //     name: "Box of gifts",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'holidays',
    //     cost: "",
    //     image: "/products/j/j-15.webp",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },

    // {
    //     id: 69,
    //     name: "Box of chocolates",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'beautiful',
    //     cost: "",
    //     image: "/products/l/l-1.jpg",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 70,
    //     name: "Box of chocolates",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'beautiful',
    //     cost: "",
    //     image: "/products/l/l-2.jpg",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 71,
    //     name: "Box of chocolates",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'beautiful',
    //     cost: "",
    //     image: "/products/l/l-3.jpg",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 72,
    //     name: "Box of chocolates",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'beautiful',
    //     cost: "",
    //     image: "/products/l/l-4.jpg",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 73,
    //     name: "Box of chocolates",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'beautiful',
    //     cost: "",
    //     image: "/products/l/l-5.jpg",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 74,
    //     name: "Box of chocolates",
    //     price: "Zakaz orqali buyurtma berish",
    //     category: 'beautiful',
    //     cost: "",
    //     image: "/products/l/l-6.jpg",
    //     description: `Bayram Sovg'alari. Onalaringiz, Ayollaringiz, Sevgilingiz, Opa-singillaringiz va aka ukalaringiz uchun ajoyib tanlov.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
    // {
    //     id: 75,
    //     name: "Dasturxonlar",
    //     price: "200 000 ",
    //     category: 'unusual',
    //     cost: "so'm / 1 dona",
    //     image: "/products/h/h-2.jpg",
    //     description: `Turli xil ranglarda va turli xil shaklar bilan bezatilgan dasturxonlar. Siz turli xil variantlardan birini tanlashingiz mumkin. Ramazon bayrami uchun ajoyib tuhfa bo'ladi.`,
    //     discountPrice: 0,
    //     criterion: "1 dona",
    // },
]